# Default config file for AGN models. 

# CLOUDY VERSION
cloudy_version: c23.01

# ABUNDANCE PATTERN AND DEPLETION
metallicity: [0.001, 0.01]
reference_abundance: GalacticConcordance # the reference abundance pattern to assume
alpha: 0.0  # alpha element enhancement
abundance_scalings:
  nitrogen: GalacticConcordance # scaling for Nitrogen, either float relative to Solar or string defining the in-built function to use
  carbon: GalacticConcordance # scaling for Carbon, either float relative to Solar or string defining the in-built function to use
depletion_model:  # the depletion model.
depletion_scale:

# GRAINS
grains: 

# GEOMETRY
geometry: planeparallel

# IONISATION PARAMETER 
ionisation_parameter_model: fixed  # which ionisation parameter model to use. `ref` assumes a varying ionisation parameter at a fixed reference age and metallicity
ionisation_parameter: [0.01, 0.1]  

# DENSITY
hydrogen_density: [1.0e+4, 1.0e+10]

# STOPPING CRITERIA
stop_column_density: [22, 23]  # stopping column density

# MISC COMMANDS
CMB: false  # include CMB heating
T_floor: 100  # lower gas temperature floor
cosmic_rays: true  # flag for inclusion of cosmic ray heating
# covering_factor: 1.0  #

turbulence: 100 # turbulence
z: 0.0  # redshift

# OUTPUT COMMANDS
resolution: 1.0 # energy resolution relative to the default
output_cont: true
output_linelist: linelist.dat
iterate_to_convergence: